#!/usr/bin/env bash
# glass-theme.sh — Glass mode toggle for Hyprland
# Usage: glass-theme.sh [on|off|toggle|status]
#
# Glass mode applies:
#   - Real transparency on all surfaces
#   - Enhanced compositor blur
#   - Translucent Waybar, Rofi, Foot, Kitty
#   - Colors derived from current wallpaper via pywal
#
# This does NOT change the wallpaper or pywal colors.
# It only changes the RENDERING of the current theme.

set -euo pipefail

DOTFILES="$HOME/.dotfiles"
WAL_CACHE="$HOME/.cache/wal"
STATE="$HOME/.cache/.glass-theme"
BACKUP_DIR="$HOME/.cache/.glass-backup"

# ── Helpers ────────────────────────────────────────────────────

read_wal_colors() {
    local colors_file="$WAL_CACHE/colors"
    if [ ! -f "$colors_file" ]; then
        echo "[glass] No pywal colors found. Run 'wal -i <wallpaper>' first." >&2
        return 1
    fi
    mapfile -t C < "$colors_file"
}

hex_to_rgb() {
    local hex="${1#\#}"
    printf "%d, %d, %d" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

# ── Generate Glass Waybar CSS ──────────────────────────────────

generate_waybar_glass() {
    read_wal_colors || return 1

    local bg_rgb; bg_rgb=$(hex_to_rgb "${C[0]}")
    local fg="${C[7]}"
    local c1="${C[1]}"
    local c4="${C[4]}"
    local c8="${C[8]}"

    cat > "$DOTFILES/waybar/style-glass.css" << CSS
/* ═══════════════════════════════════════════════════════════════
   Glass Waybar — generated by glass-theme.sh
   Translucent surfaces with wallpaper-derived colors
   ═══════════════════════════════════════════════════════════════ */

* {
    border: none;
    border-radius: 0;
    font-family: JetBrainsMono Nerd Font, monospace;
    font-weight: bold;
    font-size: 14px;
    min-height: 0;
}

window#waybar {
    background: rgba($bg_rgb, 0.30);
    color: $fg;
}

/* ── Workspaces ─────────────────────────────────────────── */

#workspaces button {
    padding: 5px;
    color: rgba(160, 165, 185, 0.60);
    margin-right: 5px;
}

#workspaces button.active {
    color: $fg;
}

#workspaces button.focused {
    color: $fg;
    background: rgba($bg_rgb, 0.45);
    border-radius: 10px;
}

#workspaces button.urgent {
    color: #fff;
    background: rgba(240, 100, 100, 0.55);
    border-radius: 10px;
}

#workspaces button:hover {
    background: rgba(255, 255, 255, 0.08);
    color: $fg;
    border-radius: 10px;
}

/* ── Modules ────────────────────────────────────────────── */

#custom-window,
#clock,
#battery,
#pulseaudio,
#network,
#cpu,
#memory,
#workspaces,
#tray,
#backlight {
    background: rgba($bg_rgb, 0.35);
    padding: 0px 10px;
    margin: 3px 0px;
    margin-top: 5px;
}

#backlight {
    border-radius: 10px 0px 0px 10px;
}

#tray {
    border-radius: 10px;
    margin-right: 10px;
}

#workspaces {
    background: rgba($bg_rgb, 0.35);
    border-radius: 10px;
    margin-left: 10px;
    padding-right: 0px;
    padding-left: 5px;
}

#cpu {
    border-radius: 0px 10px 10px 0px;
    margin-right: 10px;
}

#memory {
    border-radius: 10px 0px 0px 10px;
}

#custom-window {
    background: rgba($bg_rgb, 0.25);
    border-radius: 10px;
    margin-left: 60px;
    margin-right: 60px;
}

#clock {
    color: $fg;
    border-radius: 10px;
    margin-left: 5px;
    border-right: 0px;
}

#network {
    color: $fg;
    border-radius: 10px 0px 0px 10px;
}

#pulseaudio {
    color: $fg;
    border-left: 0px;
    border-right: 0px;
}

#pulseaudio.microphone {
    color: $fg;
    border-radius: 0px 10px 10px 0px;
    border-left: 0px;
    border-right: 0px;
    margin-right: 5px;
}

#battery {
    color: $fg;
    border-radius: 0px 10px 10px 0px;
    margin-right: 10px;
}

#custom-recording {
    color: $c1;
    background: rgba($bg_rgb, 0.35);
    border-radius: 10px;
    padding: 0 10px;
    margin: 3px 0px;
    margin-top: 5px;
    margin-right: 5px;
    font-size: 14px;
}

#custom-moon {
    color: $fg;
    background: rgba($bg_rgb, 0.35);
    border-radius: 10px;
    padding: 0px 10px;
    margin: 3px 0px;
    margin-top: 5px;
    margin-left: 5px;
}

#custom-pomodoro {
    background: rgba($bg_rgb, 0.25);
    color: rgba(180, 170, 160, 0.75);
    border-radius: 10px;
    padding: 0px 10px;
    margin: 3px 0px;
    margin-top: 5px;
    margin-left: 5px;
}

#custom-pomodoro.work {
    background: rgba($bg_rgb, 0.25);
    color: rgba(231, 158, 176, 0.85);
}

#custom-pomodoro.break {
    background: rgba($bg_rgb, 0.25);
    color: rgba(149, 171, 228, 0.85);
}

#custom-pomodoro.paused {
    background: rgba($bg_rgb, 0.25);
    color: rgba(139, 142, 145, 0.65);
}
CSS
}

# ── Generate Glass Rofi Config ─────────────────────────────────

generate_rofi_glass() {
    read_wal_colors || return 1

    local bg_rgb; bg_rgb=$(hex_to_rgb "${C[0]}")
    local fg="${C[7]}"
    local sel_rgb; sel_rgb=$(hex_to_rgb "${C[4]}")

    cat > "$DOTFILES/rofi/glass.rasi" << RASI
/* ═══════════════════════════════════════════════════════════════
   Glass Rofi — generated by glass-theme.sh
   Translucent glass surface with wallpaper-derived colors
   ═══════════════════════════════════════════════════════════════ */

configuration {
    modi: "drun,run,window";
    show-icons: true;
    icon-theme: "Papirus";
    display-drun: "Apps";
    display-run: "Run";
    display-window: "Windows";
    drun-display-format: "{name}";
    font: "JetBrains Mono Nerd Font 10";
}

* {
    border: 0;
    margin: 0;
    padding: 0;
    spacing: 0;
    background-color: transparent;
    text-color: $fg;
}

window {
    transparency: "real";
    background-color: rgba($bg_rgb, 0.55);
    border: 1px solid rgba($sel_rgb, 0.35);
    border-radius: 12px;
    width: 600px;
    padding: 0;
}

mainbox {
    background-color: transparent;
    padding: 10px;
}

inputbar {
    background-color: rgba(255, 255, 255, 0.06);
    border-radius: 8px;
    padding: 10px;
    spacing: 10px;
    children: [ prompt, entry ];
}

prompt {
    text-color: rgba($sel_rgb, 0.9);
}

entry {
    text-color: $fg;
    placeholder: "Search...";
    placeholder-color: rgba(160, 165, 185, 0.5);
}

listview {
    background-color: transparent;
    columns: 1;
    lines: 8;
    spacing: 3px;
    padding: 8px 0 0 0;
}

element {
    background-color: transparent;
    text-color: $fg;
    border-radius: 6px;
    padding: 8px 10px;
}

element normal.normal {
    background-color: transparent;
}

element alternate.normal {
    background-color: transparent;
}

element selected.normal {
    background-color: rgba($sel_rgb, 0.30);
    text-color: #ffffff;
}

element-icon {
    size: 24px;
    padding: 0 10px 0 0;
}

element-text {
    text-color: inherit;
}
RASI
}

# ── Generate Glass Foot Config ─────────────────────────────────

generate_foot_glass() {
    read_wal_colors || return 1

    local bg="${C[0]#\#}"
    local fg="${C[7]#\#}"

    cat > "$DOTFILES/foot/foot-glass.ini" << INI
[main]
font=JetBrainsMono Nerd Font:size=15
shell=fish
alpha=0.65

[colors-dark]
background=$bg
foreground=$fg
regular0=${C[0]#\#}
regular1=${C[1]#\#}
regular2=${C[2]#\#}
regular3=${C[3]#\#}
regular4=${C[4]#\#}
regular5=${C[5]#\#}
regular6=${C[6]#\#}
regular7=${C[7]#\#}
bright0=${C[8]#\#}
bright1=${C[9]#\#}
bright2=${C[10]#\#}
bright3=${C[11]#\#}
bright4=${C[12]#\#}
bright5=${C[13]#\#}
bright6=${C[14]#\#}
bright7=${C[15]#\#}

[cursor]
style=beam

[key-bindings]
scrollback-up-page=Control+Shift+Page_Up
scrollback-down-page=Control+Shift+Page_Down

[mouse-bindings]
primary-paste=BTN_MIDDLE
INI
}

# ── Apply Glass ────────────────────────────────────────────────

apply_glass() {
    read_wal_colors || return 1

    # Backup current configs
    mkdir -p "$BACKUP_DIR"
    cp "$DOTFILES/foot/foot.ini" "$BACKUP_DIR/foot.ini" 2>/dev/null || true
    cp "$DOTFILES/waybar/style.css" "$BACKUP_DIR/style.css" 2>/dev/null || true
    cp "$DOTFILES/rofi/config.rasi" "$BACKUP_DIR/config.rasi" 2>/dev/null || true

    # Generate all Glass configs from current pywal colors
    generate_waybar_glass
    generate_rofi_glass
    generate_foot_glass

    # ── Hyprland: glass decoration ──
    hyprctl keyword decoration:active_opacity 0.78 >/dev/null
    hyprctl keyword decoration:inactive_opacity 0.65 >/dev/null
    hyprctl keyword decoration:blur:size 12 >/dev/null
    hyprctl keyword decoration:blur:passes 4 >/dev/null
    hyprctl keyword decoration:blur:noise "0.02" >/dev/null
    hyprctl keyword decoration:blur:contrast "0.9" >/dev/null
    hyprctl keyword decoration:blur:brightness "0.85" >/dev/null
    hyprctl keyword decoration:blur:vibrancy "0.2" >/dev/null
    hyprctl keyword decoration:blur:vibrancy_darkness "0.5" >/dev/null
    hyprctl keyword decoration:shadow:enabled true >/dev/null
    hyprctl keyword decoration:shadow:range 8 >/dev/null
    hyprctl keyword decoration:shadow:render_power 4 >/dev/null
    hyprctl keyword decoration:shadow:color "rgba(0,0,0,0.4)" >/dev/null
    hyprctl keyword general:border_size 1 >/dev/null

    # ── Waybar: apply Glass CSS ──
    cp "$DOTFILES/waybar/style-glass.css" "$DOTFILES/waybar/style.css"
    echo "glass" > "$DOTFILES/waybar/.theme-mode"
    pkill waybar 2>/dev/null || true
    sleep 0.3
    waybar &>/dev/null &
    disown

    # ── Foot: apply Glass config ──
    cp "$DOTFILES/foot/foot-glass.ini" "$DOTFILES/foot/foot.ini"
    cp "$DOTFILES/foot/foot.ini" "$HOME/.config/foot/foot.ini" 2>/dev/null || true

    # ── Kitty: apply Glass opacity ──
    echo "# Glass overrides — auto-generated by glass-theme.sh
background_opacity 0.70
" > "$DOTFILES/kitty/glass.conf"

    # ── Rofi: apply Glass theme ──
    cp "$DOTFILES/rofi/glass.rasi" "$DOTFILES/rofi/config.rasi"
    cp "$DOTFILES/rofi/config.rasi" "$HOME/.config/rofi/config.rasi" 2>/dev/null || true

    # ── State ──
    echo "on" > "$STATE"
    notify-send "🔮 Glass" "Glass mode enabled" -t 2000 2>/dev/null || true
    echo "[glass] Glass mode enabled"
}

# ── Remove Glass ───────────────────────────────────────────────

remove_glass() {
    # ── Hyprland: restore defaults ──
    hyprctl keyword decoration:active_opacity 1.0 >/dev/null
    hyprctl keyword decoration:inactive_opacity 1.0 >/dev/null
    hyprctl keyword decoration:blur:size 3 >/dev/null
    hyprctl keyword decoration:blur:passes 1 >/dev/null
    hyprctl keyword decoration:blur:noise "0.02" >/dev/null
    hyprctl keyword decoration:blur:contrast "0.9" >/dev/null
    hyprctl keyword decoration:blur:brightness "0.85" >/dev/null
    hyprctl keyword decoration:blur:vibrancy "0.18" >/dev/null
    hyprctl keyword decoration:blur:vibrancy_darkness "0.5" >/dev/null
    hyprctl keyword decoration:shadow:enabled true >/dev/null
    hyprctl keyword decoration:shadow:range 4 >/dev/null
    hyprctl keyword decoration:shadow:render_power 3 >/dev/null
    hyprctl keyword decoration:shadow:color "rgba(1a1a1aee)" >/dev/null
    hyprctl keyword general:border_size 2 >/dev/null

    # ── Restore Waybar ──
    if [ -f "$BACKUP_DIR/style.css" ]; then
        cp "$BACKUP_DIR/style.css" "$DOTFILES/waybar/style.css"
    fi
    echo "fixed" > "$DOTFILES/waybar/.theme-mode"
    pkill waybar 2>/dev/null || true
    sleep 0.3
    waybar &>/dev/null &
    disown

    # ── Restore Foot ──
    if [ -f "$BACKUP_DIR/foot.ini" ]; then
        cp "$BACKUP_DIR/foot.ini" "$DOTFILES/foot/foot.ini"
        cp "$DOTFILES/foot/foot.ini" "$HOME/.config/foot/foot.ini" 2>/dev/null || true
    fi

    # ── Restore Kitty ──
    rm -f "$DOTFILES/kitty/glass.conf"

    # ── Restore Rofi ──
    if [ -f "$BACKUP_DIR/config.rasi" ]; then
        cp "$BACKUP_DIR/config.rasi" "$DOTFILES/rofi/config.rasi"
        cp "$DOTFILES/rofi/config.rasi" "$HOME/.config/rofi/config.rasi" 2>/dev/null || true
    fi

    # ── State ──
    rm -f "$STATE"
    notify-send "🔮 Glass" "Glass mode disabled" -t 2000 2>/dev/null || true
    echo "[glass] Glass mode disabled"
}

# ── Main ───────────────────────────────────────────────────────

case "${1:-toggle}" in
    on)
        apply_glass
        ;;
    off)
        remove_glass
        ;;
    toggle)
        if [ -f "$STATE" ]; then
            remove_glass
        else
            apply_glass
        fi
        ;;
    status)
        if [ -f "$STATE" ]; then
            echo "glass"
        else
            echo "off"
        fi
        ;;
    *)
        echo "Usage: glass-theme.sh [on|off|toggle|status]"
        exit 1
        ;;
esac
