#!/usr/bin/env bash
# glass-theme.sh — Glass mode toggle for Hyprland
# Usage: glass-theme.sh [on|off|toggle|status]
#
# Glass mode applies:
#   - Real transparency on all surfaces
#   - Enhanced compositor blur
#   - Translucent Waybar, Rofi, Foot, Kitty
#   - Colors derived from current wallpaper via pywal
#
# This does NOT change the wallpaper or pywal colors.
# It only changes the RENDERING of the current theme.

set -euo pipefail

DOTFILES="$HOME/.dotfiles"
WAL_CACHE="$HOME/.cache/wal"
STATE="$HOME/.cache/.glass-theme"
BACKUP_DIR="$HOME/.cache/.glass-backup"

# ── Helpers ────────────────────────────────────────────────────

read_wal_colors() {
    local colors_file="$WAL_CACHE/colors"
    if [ ! -f "$colors_file" ]; then
        echo "[glass] No pywal colors found. Run 'wal -i <wallpaper>' first." >&2
        return 1
    fi
    mapfile -t C < "$colors_file"
}

hex_to_rgb() {
    local hex="${1#\#}"
    printf "%d, %d, %d" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

# ── Generate Glass Waybar CSS ──────────────────────────────────

generate_waybar_glass() {
    read_wal_colors || return 1

    local bg_rgb; bg_rgb=$(hex_to_rgb "${C[0]}")
    local fg="${C[7]}"
    local fg_rgb; fg_rgb=$(hex_to_rgb "${C[7]}")
    local c1="${C[1]}"
    local c4="${C[4]}"
    local c4_rgb; c4_rgb=$(hex_to_rgb "${C[4]}")
    local c5="${C[5]}"
    local c5_rgb; c5_rgb=$(hex_to_rgb "${C[5]}")
    local c6="${C[6]}"
    local c6_rgb; c6_rgb=$(hex_to_rgb "${C[6]}")
    local c8="${C[8]}"

    cat > "$DOTFILES/waybar/style-glass.css" << CSS
/* ═══════════════════════════════════════════════════════════════
   Glass Waybar — generated by glass-theme.sh
   Translucent surfaces with wallpaper-derived colors
   ═══════════════════════════════════════════════════════════════ */

* {
    border: none;
    box-shadow: none;
    border-radius: 0;
    font-family: JetBrainsMono Nerd Font, monospace;
    font-weight: bold;
    font-size: 13px;
    min-height: 0;
}

window#waybar,
window#waybar > box,
.modules-left,
.modules-center,
.modules-right {
    background-color: rgba(0, 0, 0, 0);
    background: transparent;
    background-image: none;
    border: none;
    box-shadow: none;
    color: $fg;
}

/* ── Workspaces ─────────────────────────────────────────── */

#workspaces {
    background: rgba($bg_rgb, 0.42);
    border: none;
    box-shadow: none;
    border-radius: 10px;
    margin: 2px 4px;
    padding: 2px 3px;
}

#workspaces button {
    padding: 1px 7px;
    color: rgba($fg_rgb, 0.75);
    margin: 0 1px;
    border: 1px solid transparent;
    box-shadow: none;
    border-radius: 7px;
    background: transparent;
}

#workspaces button.active {
    color: #ffffff;
    background: rgba($c6_rgb, 0.38);
    border: 1px solid rgba(255, 255, 255, 0.30);
    box-shadow: none;
    border-radius: 7px;
}

#workspaces button.focused {
    color: #ffffff;
    background: rgba($c6_rgb, 0.25);
    border: 1px solid rgba(255, 255, 255, 0.20);
    box-shadow: none;
    border-radius: 7px;
}

#workspaces button.urgent {
    color: #fff;
    background: rgba(240, 100, 100, 0.70);
    border: 1px solid rgba(255, 255, 255, 0.45);
    box-shadow: none;
    border-radius: 7px;
}

#workspaces button:hover {
    background: rgba($fg_rgb, 0.22);
    color: #ffffff;
    border: 1px solid rgba($fg_rgb, 0.35);
    box-shadow: none;
    border-radius: 7px;
}

/* ── Modules Flutuantes (Ilhas) ──────────────────────────── */

#custom-window,
#clock,
#battery,
#pulseaudio,
#network,
#cpu,
#memory,
#tray,
#backlight,
#custom-moon,
#custom-pomodoro,
#custom-recording {
    background: rgba($bg_rgb, 0.42);
    border: none;
    box-shadow: none;
    border-radius: 10px;
    padding: 1px 10px;
}

/* ── Ilhas Individuais ──────────────────────────────────── */

#clock {
    color: $fg;
    border-radius: 10px;
    margin: 2px 4px;
}

#custom-moon {
    color: $fg;
    border-radius: 10px;
    margin: 2px 4px;
}

#custom-pomodoro {
    color: rgba(180, 170, 160, 0.85);
    border-radius: 10px;
    margin: 2px 4px;
}

#custom-pomodoro.work {
    color: rgba(231, 158, 176, 0.95);
}

#custom-pomodoro.break {
    color: rgba(149, 171, 228, 0.95);
}

#custom-pomodoro.paused {
    color: rgba(139, 142, 145, 0.75);
}

#custom-window {
    border-radius: 10px;
    margin: 2px 4px;
}

#tray {
    border-radius: 10px;
    margin: 2px 4px;
}

#custom-recording {
    color: $c1;
    border-radius: 10px;
    margin: 2px 4px;
    font-size: 13px;
}

/* ── Grupo de Métricas (Direita) ────────────────────────── */

#memory {
    border-radius: 10px 0px 0px 10px;
    margin: 2px 0px 2px 4px;
}

#cpu,
#network,
#battery,
#backlight,
#pulseaudio {
    border-radius: 0;
    margin: 2px 0px;
}

#pulseaudio.microphone {
    border-radius: 0px 10px 10px 0px;
    margin: 2px 8px 2px 0px;
}
CSS
}

# ── Generate Glass Rofi Config ─────────────────────────────────

generate_rofi_glass() {
    read_wal_colors || return 1

    local bg_rgb; bg_rgb=$(hex_to_rgb "${C[0]}")
    local fg="${C[7]}"
    local sel_rgb; sel_rgb=$(hex_to_rgb "${C[4]}")

    cat > "$DOTFILES/rofi/glass.rasi" << RASI
/* ═══════════════════════════════════════════════════════════════
   Glass Rofi — generated by glass-theme.sh
   Translucent glass surface with wallpaper-derived colors
   ═══════════════════════════════════════════════════════════════ */

configuration {
    modi: "drun,run,window";
    show-icons: true;
    icon-theme: "Papirus";
    display-drun: "Apps";
    display-run: "Run";
    display-window: "Windows";
    drun-display-format: "{name}";
    font: "JetBrains Mono Nerd Font 10";
}

* {
    border: 0;
    margin: 0;
    padding: 0;
    spacing: 0;
    background-color: transparent;
    text-color: #e0e0e5;
}

window {
    transparency: "real";
    background-color: rgba($bg_rgb, 0.55);
    border: 1px;
    border-color: rgba(255, 255, 255, 0.25);
    border-radius: 14px;
    width: 620px;
    padding: 12px;
}

mainbox {
    background-color: transparent;
    padding: 0;
    spacing: 10px;
    children: [ inputbar, listview ];
}

inputbar {
    background-color: rgba(255, 255, 255, 0.08);
    border: 1px;
    border-color: rgba(255, 255, 255, 0.12);
    border-radius: 10px;
    padding: 8px 12px;
    spacing: 10px;
    children: [ prompt, entry ];
}

prompt {
    text-color: rgba($sel_rgb, 0.95);
}

entry {
    text-color: #ffffff;
    placeholder: "Search...";
    placeholder-color: rgba(180, 185, 205, 0.50);
}

listview {
    background-color: transparent;
    columns: 1;
    lines: 8;
    spacing: 4px;
    padding: 6px 0 0 0;
}

element {
    background-color: transparent;
    text-color: #e0e0e5;
    border-radius: 8px;
    padding: 8px 12px;
    spacing: 12px;
}

element-icon {
    size: 24px;
    background-color: transparent;
}

element-text {
    background-color: transparent;
    text-color: inherit;
    vertical-align: 0.5;
}

element normal.normal {
    background-color: transparent;
    text-color: #e0e0e5;
}

element alternate.normal {
    background-color: transparent;
    text-color: #e0e0e5;
}

element selected.normal {
    background-color: rgba($sel_rgb, 0.45);
    text-color: #ffffff;
    border: 1px;
    border-color: rgba(255, 255, 255, 0.30);
    border-radius: 8px;
}

element normal.active,
element alternate.active {
    background-color: transparent;
    text-color: #ffffff;
}

element selected.active {
    background-color: rgba($sel_rgb, 0.55);
    text-color: #ffffff;
}
RASI
}

# ── Generate Glass Foot Config ─────────────────────────────────

generate_foot_glass() {
    read_wal_colors || return 1

    local bg="${C[0]#\#}"
    local fg="${C[7]#\#}"

    cat > "$DOTFILES/foot/foot-glass.ini" << INI
[main]
font=JetBrainsMono Nerd Font:size=15
shell=fish
alpha=0.65

[colors-dark]
background=$bg
foreground=$fg
regular0=${C[0]#\#}
regular1=${C[1]#\#}
regular2=${C[2]#\#}
regular3=${C[3]#\#}
regular4=${C[4]#\#}
regular5=${C[5]#\#}
regular6=${C[6]#\#}
regular7=${C[7]#\#}
bright0=${C[8]#\#}
bright1=${C[9]#\#}
bright2=${C[10]#\#}
bright3=${C[11]#\#}
bright4=${C[12]#\#}
bright5=${C[13]#\#}
bright6=${C[14]#\#}
bright7=${C[15]#\#}

[cursor]
style=beam

[key-bindings]
scrollback-up-page=Control+Shift+Page_Up
scrollback-down-page=Control+Shift+Page_Down

[mouse-bindings]
primary-paste=BTN_MIDDLE
INI
}

# ── Apply Glass ────────────────────────────────────────────────

apply_glass() {
    read_wal_colors || return 1

    # Backup current configs
    mkdir -p "$BACKUP_DIR"
    cp "$DOTFILES/foot/foot.ini" "$BACKUP_DIR/foot.ini" 2>/dev/null || true
    cp "$DOTFILES/waybar/style.css" "$BACKUP_DIR/style.css" 2>/dev/null || true
    cp "$DOTFILES/rofi/config.rasi" "$BACKUP_DIR/config.rasi" 2>/dev/null || true

    # State flag — define ANTES do reload para o hyprland.lua detectar
    echo "on" > "$STATE"

    # Generate all Glass configs from current pywal colors
    generate_waybar_glass
    generate_rofi_glass
    generate_foot_glass

    # ── Waybar: apply Glass CSS ──
    cp "$DOTFILES/waybar/style-glass.css" "$DOTFILES/waybar/style.css"
    cp "$DOTFILES/waybar/style-glass.css" "$HOME/.config/waybar/style.css" 2>/dev/null || true
    echo "glass" > "$DOTFILES/waybar/.theme-mode"
    pkill -x waybar 2>/dev/null || true
    sleep 0.5
    setsid waybar >/dev/null 2>&1 &

    # ── Foot: apply Glass config ──
    cp "$DOTFILES/foot/foot-glass.ini" "$DOTFILES/foot/foot.ini"
    cp "$DOTFILES/foot/foot.ini" "$HOME/.config/foot/foot.ini" 2>/dev/null || true

    # ── Rofi: apply Glass theme ──
    cp "$DOTFILES/rofi/glass.rasi" "$DOTFILES/rofi/config.rasi"
    cp "$DOTFILES/rofi/config.rasi" "$HOME/.config/rofi/config.rasi" 2>/dev/null || true

    # ── Hyprland: recarrega a configuração nativa com suporte completo a Glass ──
    hyprctl reload

    notify-send "🔮 Glass" "Tema Glass ativado com as cores do wallpaper" -t 2000 2>/dev/null || true
    echo "[glass] Glass mode enabled"
}

# ── Refresh Glass (quando o wallpaper/cores mudam) ──────────────

refresh_glass() {
    if [ ! -f "$STATE" ]; then
        return 0
    fi
    read_wal_colors || return 1

    generate_waybar_glass
    generate_rofi_glass
    generate_foot_glass

    cp "$DOTFILES/waybar/style-glass.css" "$DOTFILES/waybar/style.css"
    cp "$DOTFILES/waybar/style-glass.css" "$HOME/.config/waybar/style.css" 2>/dev/null || true
    pkill -x waybar 2>/dev/null || true
    sleep 0.5
    setsid waybar >/dev/null 2>&1 &

    cp "$DOTFILES/rofi/glass.rasi" "$DOTFILES/rofi/config.rasi"
    cp "$DOTFILES/rofi/config.rasi" "$HOME/.config/rofi/config.rasi" 2>/dev/null || true

    hyprctl reload
    echo "[glass] Glass theme refreshed with new wallpaper colors"
}

# ── Remove Glass ───────────────────────────────────────────────

remove_glass() {
    rm -f "$STATE"

    # ── Restore Waybar ──
    WAL_CSS="$HOME/.cache/wal/colors-waybar.css"
    if [ -f "$WAL_CSS" ]; then
        cp "$WAL_CSS" "$DOTFILES/waybar/style.css"
        cp "$WAL_CSS" "$HOME/.config/waybar/style.css" 2>/dev/null || true
    elif [ -f "$BACKUP_DIR/style.css" ]; then
        cp "$BACKUP_DIR/style.css" "$DOTFILES/waybar/style.css"
        cp "$BACKUP_DIR/style.css" "$HOME/.config/waybar/style.css" 2>/dev/null || true
    fi
    echo "pywal" > "$DOTFILES/waybar/.theme-mode"
    pkill waybar 2>/dev/null || true
    sleep 0.3
    waybar &>/dev/null &
    disown

    # ── Restore Foot ──
    if [ -f "$BACKUP_DIR/foot.ini" ]; then
        cp "$BACKUP_DIR/foot.ini" "$DOTFILES/foot/foot.ini"
        cp "$DOTFILES/foot/foot.ini" "$HOME/.config/foot/foot.ini" 2>/dev/null || true
    fi

    # ── Restore Kitty ──
    rm -f "$DOTFILES/kitty/glass.conf"

    # ── Restore Rofi ──
    if [ -f "$BACKUP_DIR/config.rasi" ]; then
        cp "$BACKUP_DIR/config.rasi" "$DOTFILES/rofi/config.rasi"
        cp "$DOTFILES/rofi/config.rasi" "$HOME/.config/rofi/config.rasi" 2>/dev/null || true
    fi

    # ── State ──
    rm -f "$STATE"

    # ── Hyprland: recarrega para restaurar o look padrão ──
    hyprctl reload

    notify-send "🔮 Glass" "Tema Glass desativado" -t 2000 2>/dev/null || true
    echo "[glass] Glass mode disabled"
}

# ── Main ───────────────────────────────────────────────────────

case "${1:-toggle}" in
    on)
        apply_glass
        ;;
    off)
        remove_glass
        ;;
    refresh)
        refresh_glass
        ;;
    toggle)
        if [ -f "$STATE" ]; then
            remove_glass
        else
            apply_glass
        fi
        ;;
    status)
        if [ -f "$STATE" ]; then
            echo "glass"
        else
            echo "off"
        fi
        ;;
    *)
        echo "Usage: glass-theme.sh [on|off|refresh|toggle|status]"
        exit 1
        ;;
esac
