WALLPAPER_DIR="$HOME/Pictures/Wallpapers"
LIGHT_WALLPAPER="wallhaven-6d5y86.jpg"
DARK_WALLPAPER="wallhaven-rdx51q.jpg"

LIGHT_START="06:00"
DARK_START="18:00"

LIGHT_PRESET="light"
DARK_PRESET="dark"   # trocar para "muted" quando quiser

FILTER_START="20:00"
FILTER_END="06:00"
