WALLPAPER_DIR="$HOME/Pictures/Wallpapers"
LIGHT_WALLPAPER="image.jpg"
DARK_WALLPAPER="wallhaven-95gwvx.jpg"

LIGHT_START="06:00"
DARK_START="18:00"

LIGHT_PRESET="light"
DARK_PRESET="mono"

LIGHT_GTK_THEME="Adwaita"
DARK_GTK_THEME="Adwaita-dark"

FILTER_START="20:00"
FILTER_END="06:00"
